require:
 - rubocop-capybara
 - rubocop-factory_bot
 - rubocop-performance
 - rubocop-rails
 - rubocop-rspec
 - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Exclude:
    - 'config/initializers/**/*'

Style/EmptyMethod:
  Exclude:
    - 'spec/support/feature/**/*'

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
