brew "ansible"
brew "autojump"
brew "asdf"
brew "awscli"
brew "ctags"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "ffmpeg"
brew "fd"
brew "fzf"
brew "git"
brew "gpg"
brew "graphviz"
brew "heroku"
brew "hub"
brew "jemalloc"
brew "languagetool"
brew "libxml2"
brew "libxslt"
brew "mas"
brew "memcached"
brew "neovim"
brew "node"
brew "openssl"
brew "pgcli"
brew "python@3"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "ruby-build"
brew "s3cmd"
brew "the_silver_searcher"
brew "tmux"
brew "webp"
brew "x264"
brew "x265"
brew "xvid"
brew "yarn"
brew "zsh"

tap "heroku/brew"
brew "heroku"

tap "thoughtbot/formulae"
brew "rcm"

tap "homebrew/cask"
cask_args appdir: "/Applications"
cask "adoptopenjdk"
cask "appcleaner"
cask "alfred"
cask "bartender"
cask "fork"
cask "hazel"
cask "kap"
cask "postgres-unofficial"
cask "spotify"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlvideo"

mas "Irvue", id: 1039633667
mas "1Password7", id: 1333542190
mas "Magnet", id: 441258766
mas "Pixelmator", id: 407963104
