#!/bin/sh

if [ ! -e ~/.bin/vim ]; then
  echo "Creating symlink from ~/.bin/vim to NeoVim bin."
  ln -s `which nvim` ~/.bin/vim
fi

# Test if the neovim pip module is installed
python -c "import neovim" >& /dev/null

# If not, install it
if [ "${?}" == "1" ]; then
  # If this doesn't work, see:
  # http://stackoverflow.com/questions/20082935/how-to-install-pip-for-python3-on-mac-os-x
  echo "Installing NeoVim pip module."
  pip3 install neovim
fi

# install plug vim plugin if it's not there already
if [ ! -e ~/.config/nvim/autoload/plug.vim ]; then
  echo "Installing plug.vim."
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

rcup -x setup -t ansible -t git -t nvim -t rbenv -t rspec -t tmux -t zsh

echo "Setup complete."
