#!/bin/sh

# Use homebrew to install packages found in both `./Brewfile` and `~/.Brewfile`
# A bit redundant since they eventually point to the same file but it's a good
# way to work in case one doesn't exist

brew bundle
brew bundle --file=~/.Brewfile

if ! grep -Fxq "/usr/local/bin/zsh" /etc/shells
then 
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
fi

chsh -s /usr/local/bin/zsh

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [ ! -e ~/.bin/vim ]; then
  echo "Creating symlink from ~/.bin/vim to NeoVim bin."
  ln -s `which nvim` ~/.bin/vim
fi

# Test if the neovim pip2 module is installed
python2 -c "import neovim" >& /dev/null

# If not, install it
if [ "${?}" == "1" ]; then
  # If this doesn't work, see:
  # http://stackoverflow.com/questions/20082935/how-to-install-pip-for-python3-on-mac-os-x
  echo "Installing NeoVim pip2 module."
  pip2 install neovim
fi

# Test if the neovim pip2 module is installed
python3 -c "import neovim" >& /dev/null

# If not, install it
if [ "${?}" == "1" ]; then
  # If this doesn't work, see:
  # http://stackoverflow.com/questions/20082935/how-to-install-pip-for-python3-on-mac-os-x
  echo "Installing NeoVim pip3 module."
  pip3 install neovim
fi

# install plug vim plugin if it's not there already
if [ ! -e ~/.config/nvim/autoload/plug.vim ]; then
  echo "Installing plug.vim."
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

rcup -x setup -t ansible -t git -t nvim -t rbenv -t rspec -t tmux -t zsh

# install standard-format for js auto-formatting purposes
npm install -g standard standard-format neovim typescript

sudo gem install neovim

echo "Setup complete."
