let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsSnippetsDir="~/.dotfiles/tag-nvim/config/nvim/UltiSnips"
let g:UltiSnipsEnableSnipMate="1"
