# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# source private zshrc file not kept in source control
[[ -f ~/.zshrc_private ]] && source ~/.zshrc_private

# source the base zshrc configurations first
for config_file (~/.config/zsh/*.zsh) source $config_file

# fuzzy find in history
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 | grep -v "clear; echo" || history) | fzf +s --tac | sed 's/^[[:space:]]*[0-9]*[\*\ ]*//g' )
}

[ -s "$HOME/.asdf/asdf.sh" ]                          && . "$HOME/.asdf/asdf.sh"
[ -s "$HOMEBREW_HOME/nvm/nvm.sh" ]                    && . "$HOMEBREW_HOME/nvm/nvm.sh"
[ -s "$HOMEBREW_HOME/nvm/etc/bash_completion.d/nvm" ] && . "$HOMEBREW_HOME/nvm/etc/bash_completion.d/nvm"

# run this stuff every time I cd into directory
function chpwd() {
  [[ -f .heroku ]] && heroku accounts:set `cat .heroku`
}

# Start an http server in $PWD
# Usage: httpserver port
httpserver() {
  # Check if a port was provided
  if [ -z "$1" ]; then
    echo "No port provided. Please pass a port number"
    return 1
  fi

  python -m SimpleHTTPServer $1
}

# Usage: mkhtml filename.html
mkhtml() {
  # Check if a filename was provided
  if [ -z "$1" ]; then
    echo "No filename provided. Please provide a filename."
    return 1
  fi

  # Create the HTML content
  cat > $1 << EOF
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Small HTML template</title>
  <meta name="description" content="A small HTML page">
  <meta name="author" content="Joel Oliveira">

  <link rel="icon" href="/favicon.ico">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <link rel="stylesheet" href="css/styles.css?v=1.0">
</head>

<body>
  <!-- content goes here... -->
  <script src="js/scripts.js"></script>
</body>
</html>
EOF

  mkdir -p js
  mkdir -p css
  touch js/scripts.js
  touch css/styles.css

  echo "HTML file '$1' has been created."
}

mkcd() {
  # Check if a dirname was provided
  if [ -z "$1" ]; then
    echo "No directory name provided. Please provide a directory to create."
    return 1
  fi

  mkdir $1
  cd $1
}


# vim mode in zsh
bindkey -v

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
